server {
    listen 80;
    server_name testezinho.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name testezinho.site;

    # Caminhos dos certificados (dentro do container)
    ssl_certificate     /etc/letsencrypt/live/testezinho.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/testezinho.site/privkey.pem;

    # Otimizações de segurança SSL
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass         http://api:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        # Configurações para Streaming (Latência)
        proxy_buffering off;
        proxy_read_timeout 300s;
    }
}